### ISSUE TITLE
menu does not work

### ISSUE THREAD

**Issue by waskord** [5Avian/proxvc#4]
when I try to open the proxyVC menu, I get kicked out of the server with an error window

error:
```
Minecraft: Better than Adventure! 7.1_01
OS: Windows 11 (amd64) version 10.0
Java: 1.8.0_371, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.4
OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 version 4.6.0 NVIDIA 546.33, NVIDIA Corporation

java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
    at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:336)
    at org.lwjgl.MemoryUtil.decode(MemoryUtil.java:305)
    at org.lwjgl.MemoryUtil.decodeUTF8(MemoryUtil.java:294)
    at org.lwjgl.openal.ALC10.alcGetString(ALC10.java:157)
    at fiveavian.proxvc.gui.GuiVCOptions.<init>(GuiVCOptions.java:18)
    at fiveavian.proxvc.ProxVCClient.tick(ProxVCClient.java:161)
    at net.minecraft.client.Minecraft.handler$zbh000$proxvc$runTick(Minecraft.java:4439)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1493)
    at net.minecraft.client.Minecraft.run(Minecraft.java:792)
    at java.lang.Thread.run(Unknown Source)
```
image:
![image](https://github.com/5Avian/proxvc/assets/120677399/b1d4a6a1-fb17-46eb-914a-e0e3c8f20734)

**Comment by 5Avian** [comment]
hi, this is a known issue. sadly the implementation for the `decodeUTF8` function in old Java versions is wrong (or LWJGL misuses the function, one of the 2), and so it crashes the game. you should be able to fix this by updating Java. i personally use the Eclipse Temurin 21 JRE which works fine.

i'll look into fixing it for old versions, so i'm gonna leave this issue open for now.

**Comment by JAFYgames** [comment]
i have the same issue here, my log say:
Minecraft ran into an unexpected problem!

To prevent more problems, the current game has quit, but you can try to keep playing.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 8/18/24, 9:55 PM

Minecraft: Better than Adventure! 7.2_01
OS: Windows 10 (amd64) version 10.0
Java: 21.0.4, Azul Systems, Inc.
VM: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 5500 version 4.4.0 - Build 20.19.15.5166, Intel

java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
    at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:336)
    at org.lwjgl.MemoryUtil.decode(MemoryUtil.java:305)
    at org.lwjgl.MemoryUtil.decodeUTF8(MemoryUtil.java:294)
    at org.lwjgl.openal.ALC10.alcGetString(ALC10.java:157)
    at fiveavian.proxvc.vc.AudioInputDevice.getSpecifiers(AudioInputDevice.java:19)
    at fiveavian.proxvc.gui.MicrophoneListComponent.updateSpecifiers(MicrophoneListComponent.java:46)
    at fiveavian.proxvc.gui.MicrophoneListComponent.init(MicrophoneListComponent.java:33)
    at net.minecraft.client.gui.options.components.OptionsCategory.init(OptionsCategory.java:52)
    at net.minecraft.client.gui.options.data.OptionsPage.initComponents(OptionsPage.java:40)
    at net.minecraft.client.gui.options.GuiOptions.mouseClicked(GuiOptions.java:438)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:133)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1279)
    at net.minecraft.client.Minecraft.run(Minecraft.java:851)
    at java.base/java.lang.Thread.run(Thread.java:1583)

i install Zulu JDK and Eclipse JDK, but nothing work, i deleted others versions of java and nothing change.

**Comment by Sunitro23** [comment]
Did someone find a solution to this problem ?

**Comment by 5Avian** [comment]
thanks for reminding me this issue exists and affects people. i tried to fix it, but sadly i can't reproduce the error. could any of you test whether this version fixes the issue? if so, i'll release the new version after it's verified to be working.
[proxvc-1.5.2-files.zip](https://github.com/user-attachments/files/17558346/proxvc-1.5.2-files.zip) contains the jar file, or you can build from scratch in branch v1.5.2.

**Comment by Sunitro23** [comment]
It works ! You're a life savior, thank you !

**Comment by 5Avian** [comment]
you're welcome! i'll release the new version right away and just pray i haven't introduced any new bugs...

**Comment by RoughCipher** [comment]
Version 1.5.2
```
Minecraft ran into an unexpected problem!

To prevent more problems, the current game has quit, but you can try to keep playing.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 12/1/24, 2:47 PM

Minecraft: Better than Adventure! 7.2_01
OS: Windows 10 (amd64) version 10.0
Java: 18.0.2.1, Azul Systems, Inc.
VM: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
LWJGL: 2.9.4
OpenGL: AMD Radeon(TM) Vega 8 Graphics version 4.6.0 Compatibility Profile Context 24.9.1.240813, ATI Technologies Inc.

java.lang.RuntimeException: java.nio.charset.UnmappableCharacterException: Input length = 1
    at org.lwjgl.MemoryUtil.encode(MemoryUtil.java:282)
    at org.lwjgl.MemoryUtil.encode(MemoryUtil.java:243)
    at org.lwjgl.MemoryUtil.encodeASCII(MemoryUtil.java:202)
    at org.lwjgl.openal.ALC11.alcCaptureOpenDevice(ALC11.java:95)
    at fiveavian.proxvc.vc.AudioInputDevice.open(AudioInputDevice.java:31)
    at fiveavian.proxvc.gui.MicrophoneListComponent.selectSpecifier(MicrophoneListComponent.java:59)
    at fiveavian.proxvc.gui.MicrophoneListComponent.onMouseClick(MicrophoneListComponent.java:116)
    at net.minecraft.client.gui.options.components.OptionsCategory.onMouseClick(OptionsCategory.java:116)
    at net.minecraft.client.gui.options.GuiOptions.mouseClicked(GuiOptions.java:418)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:133)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1279)
    at net.minecraft.client.Minecraft.run(Minecraft.java:851)
    at java.base/java.lang.Thread.run(Thread.java:833)
```
I also checked with java 21 the error remains

**Comment by RoughCipher** [comment]
If the name of the microphone is written in English, there is no error
![image](https://github.com/user-attachments/assets/7679ed74-e084-4725-8038-1c3c6a1f861d)
